// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJMIeonSl0I9-wcN0wfNjf-ke-RAOgAs',
    appId: '1:18609994118:web:5e29100ba4e12b7a1b1407',
    messagingSenderId: '18609994118',
    projectId: 'alert-brain',
    authDomain: 'alert-brain.firebaseapp.com',
    storageBucket: 'alert-brain.appspot.com',
    measurementId: 'G-23N0B19WJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGitbEDSqueR3TvuuOV4DO3WmLiO5ZiA',
    appId: '1:18609994118:android:a906a2fd2d0c85171b1407',
    messagingSenderId: '18609994118',
    projectId: 'alert-brain',
    storageBucket: 'alert-brain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkkBRA88n34Mg2txAiqUSx-AAak-Wp0m4',
    appId: '1:18609994118:ios:c05bfba5d29b5f1d1b1407',
    messagingSenderId: '18609994118',
    projectId: 'alert-brain',
    storageBucket: 'alert-brain.appspot.com',
    iosBundleId: 'com.example.alertBrains',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkkBRA88n34Mg2txAiqUSx-AAak-Wp0m4',
    appId: '1:18609994118:ios:c05bfba5d29b5f1d1b1407',
    messagingSenderId: '18609994118',
    projectId: 'alert-brain',
    storageBucket: 'alert-brain.appspot.com',
    iosBundleId: 'com.example.alertBrains',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJMIeonSl0I9-wcN0wfNjf-ke-RAOgAs',
    appId: '1:18609994118:web:38b2666d229402a61b1407',
    messagingSenderId: '18609994118',
    projectId: 'alert-brain',
    authDomain: 'alert-brain.firebaseapp.com',
    storageBucket: 'alert-brain.appspot.com',
    measurementId: 'G-X7734Y0P95',
  );
}
